### ISSUE TITLE
YouTube recognition doesn't work

### ISSUE THREAD

**Issue by ghost** [Team-Cipher/Cipher-Bot#1]

**Comment by AlphaWind** [comment]
Have you tested it?

**Comment by ghost** [comment]
Well, since this is a base of the ecuacion bot. I have tested it out with Stella's bot on exiled and can confirm it is broken

**Comment by ghost** [comment]
I'm totally gonna abuse the labels

**Comment by Mystifi** [comment]
I'm pretty sure it's because the GET request is made to a deprecated feature; I don't think Google APIs supports this anymore

**Comment by ghost** [comment]
Ah ok thanks!

**Comment by ghost** [comment]
Yep, youtube screwed us over, closing issue
